# Generated by Django 6.0.2 on 2026-02-24 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=10, unique=True)),
                ('nome_empresa', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TipoAtivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lancamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('quantidade', models.DecimalField(decimal_places=4, max_digits=12)),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=12)),
                ('taxas', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('tipo_operacao', models.CharField(choices=[('C', 'Compra'), ('V', 'Venda')], max_length=1)),
                ('ativo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investimentos.ativo')),
            ],
        ),
        migrations.AddField(
            model_name='ativo',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='investimentos.tipoativo'),
        ),
    ]
