# Generated by Django 6.0.2 on 2026-02-26 01:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investimentos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('tipo', models.CharField(choices=[('CORRENTE', 'Conta Corrente'), ('INVESTIMENTO', 'Conta Investimento/Corretora'), ('POUPANCA', 'Poupança')], max_length=20)),
                ('saldo_inicial', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='Instituicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='lancamento',
            name='tipo_operacao',
            field=models.CharField(choices=[('C', 'Compra'), ('V', 'Venda'), ('D', 'Dividendo/JCP')], max_length=1),
        ),
        migrations.AddField(
            model_name='lancamento',
            name='conta',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='lancamentos', to='investimentos.conta'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='conta',
            name='instituicao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investimentos.instituicao'),
        ),
        migrations.CreateModel(
            name='MovimentacaoConta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('descricao', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('E', 'Entrada (Depósito)'), ('S', 'Saída (Saque/Pagamento)')], max_length=1)),
                ('conta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investimentos.conta')),
            ],
        ),
    ]
